### ISSUE TITLE
plot_slm_results 

### ISSUE THREAD

**Issue by mohammadhadiaarabi** [MICA-MNI/BrainStat#284]
Dear Developer,
When I run Tutorial 01: Linear Models notebook file, the plot_slm_results couldn't visualize results and only print:
[<IPython.core.display.Image object>,
 <IPython.core.display.Image object>,
 <IPython.core.display.Image object>,
 <IPython.core.display.Image object>]
I tested this tutorial in windows and Linux and unfortunately, this function couldn't show the results. 
It seems the first line "%matplotlib inline" is not sufficient to visualize the figures. 
Best,
Mohammad

**Comment by zihuaihuai** [comment]
Dear Mohammad,

Thank you for bringing this issue to our attention.

The behavior you're experiencing—where plot_slm_results returns a list of <IPython.core.display.Image object> instead of displaying the figures—is due to how the images are being handled within the Jupyter notebook environment. The plot_slm_results function returns a list of IPython Image objects, but they are not automatically displayed in the notebook output.

Here's how you can resolve this issue:

`from IPython.display import display

# Assuming 'slm' is your fitted model
images = plot_slm_results(slm)

# Loop through and display each image
for img in images:
    display(img)
`

This will display each image returned by plot_slm_results directly in your notebook.
